services:

  mqtt_broker:
    image: eclipse-mosquitto
    restart: always 
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  hub_simulator:
    build: ./hub
    container_name: hub_simulator
    volumes:
      - ./app:/src
    # command: chmod +x 'run_mqtt_publisher.sh' &&  sh -c 'run_mqtt_publisher.sh'

  server: 
    build: ./app
    container_name: server
    volumes:
      - ./app/data:/data/
    ports:
      - 8000:8000

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - 3000:3000
  
 